server:
  port: 9527

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: route1
          uri: lb://PAYMANT
          predicates:
            - Path=/paymant/**
      discovery:
        locator:
          enabled: true  #开启从注册中心动态访问路由的功能，通过服务名访问接口



eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka1.com:7001/eureka

